// <auto-generated />
using System;
using Hexagon.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hexagon.Infra.Data.Migrations
{
    [DbContext(typeof(HexagonContext))]
    [Migration("20241204103924_Adding_Permissions_Data")]
    partial class Adding_Permissions_Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hexagon.Domain.Models.Gyms.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<int?>("Area")
                        .HasColumnType("int");

                    b.Property<string>("ConstantPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.HasKey("Id");

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Gyms.GymGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("GymGalleries");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Gyms.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificateId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Gyms.SportClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassStatus")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxSubscription")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<double>("SubscriptionFee")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("SportId");

                    b.HasIndex("TrainerId");

                    b.ToTable("SportClasses");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Links.ClassUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SportClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubscriptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportClassId");

                    b.HasIndex("UserId");

                    b.ToTable("ClassUsers");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Links.GymStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("StaffId");

                    b.ToTable("GymStaffs");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Links.GymUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("UserId");

                    b.ToTable("GymUsers");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Links.UserCertificates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfTake")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlaceOftake")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("StaffId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCertificates");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Records.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Records.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CertificateId")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<TimeSpan>("HowLong")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("UserId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermissionId");

                    b.HasIndex("ParentId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            PermissionName = "ManageUsers",
                            PermissionTitle = "مدیریت کاربران"
                        },
                        new
                        {
                            PermissionId = 2,
                            ParentId = 1,
                            PermissionName = "AddUser",
                            PermissionTitle = "افزودن کاربر"
                        },
                        new
                        {
                            PermissionId = 3,
                            ParentId = 1,
                            PermissionName = "EditUser",
                            PermissionTitle = "ویرایش کاربر"
                        },
                        new
                        {
                            PermissionId = 4,
                            ParentId = 1,
                            PermissionName = "DeleteUser",
                            PermissionTitle = "حذف کاربر"
                        },
                        new
                        {
                            PermissionId = 5,
                            ParentId = 1,
                            PermissionName = "DetailUser",
                            PermissionTitle = "جزئیات کاربر"
                        },
                        new
                        {
                            PermissionId = 6,
                            ParentId = 1,
                            PermissionName = "DeleteUserForever",
                            PermissionTitle = "حذف مطلق کاربر"
                        },
                        new
                        {
                            PermissionId = 7,
                            PermissionName = "ManageRoles",
                            PermissionTitle = "مدیریت نقش ها"
                        },
                        new
                        {
                            PermissionId = 8,
                            ParentId = 7,
                            PermissionName = "AddRole",
                            PermissionTitle = "افزودن نقش"
                        },
                        new
                        {
                            PermissionId = 9,
                            ParentId = 7,
                            PermissionName = "EditRole",
                            PermissionTitle = "ویرایش نقش"
                        },
                        new
                        {
                            PermissionId = 10,
                            ParentId = 7,
                            PermissionName = "DeleteRole",
                            PermissionTitle = "حذف نقش"
                        },
                        new
                        {
                            PermissionId = 11,
                            ParentId = 7,
                            PermissionName = "DetailRole",
                            PermissionTitle = "جزئیات نقش"
                        },
                        new
                        {
                            PermissionId = 12,
                            ParentId = 7,
                            PermissionName = "DeleteRoleForever",
                            PermissionTitle = "حذف مطلق نقش"
                        },
                        new
                        {
                            PermissionId = 13,
                            PermissionName = "ManageTrainers",
                            PermissionTitle = "مدیریت مربی ها"
                        },
                        new
                        {
                            PermissionId = 14,
                            ParentId = 13,
                            PermissionName = "AddTrainer",
                            PermissionTitle = "افزودن مربی"
                        },
                        new
                        {
                            PermissionId = 15,
                            ParentId = 13,
                            PermissionName = "EditTrainer",
                            PermissionTitle = "ویرایش مربی"
                        },
                        new
                        {
                            PermissionId = 16,
                            ParentId = 13,
                            PermissionName = "DeleteTrainer",
                            PermissionTitle = "حذف مربی"
                        },
                        new
                        {
                            PermissionId = 17,
                            ParentId = 13,
                            PermissionName = "DetailTrainer",
                            PermissionTitle = "جزئیات مربی"
                        },
                        new
                        {
                            PermissionId = 18,
                            ParentId = 13,
                            PermissionName = "DeleteTrainerForever",
                            PermissionTitle = "حذف مطلق مربی"
                        },
                        new
                        {
                            PermissionId = 19,
                            PermissionName = "ManageCadres",
                            PermissionTitle = "مدیریت کادرها"
                        },
                        new
                        {
                            PermissionId = 20,
                            ParentId = 19,
                            PermissionName = "AddCadre",
                            PermissionTitle = "افزودن کادر"
                        },
                        new
                        {
                            PermissionId = 21,
                            ParentId = 19,
                            PermissionName = "EditCadre",
                            PermissionTitle = "ویرایش کادر"
                        },
                        new
                        {
                            PermissionId = 22,
                            ParentId = 19,
                            PermissionName = "DeleteCadre",
                            PermissionTitle = "حذف کادر"
                        },
                        new
                        {
                            PermissionId = 23,
                            ParentId = 19,
                            PermissionName = "DetailCadre",
                            PermissionTitle = "جزئیات کادر"
                        },
                        new
                        {
                            PermissionId = 24,
                            ParentId = 19,
                            PermissionName = "DeleteCadreForever",
                            PermissionTitle = "حذف مطلق کادر"
                        },
                        new
                        {
                            PermissionId = 25,
                            PermissionName = "ManageCertificates",
                            PermissionTitle = "مدیریت مدرک ها"
                        },
                        new
                        {
                            PermissionId = 26,
                            ParentId = 25,
                            PermissionName = "AddCertificate",
                            PermissionTitle = "افزودن مدرک"
                        },
                        new
                        {
                            PermissionId = 27,
                            ParentId = 25,
                            PermissionName = "EditCertificate",
                            PermissionTitle = "ویرایش مدرک"
                        },
                        new
                        {
                            PermissionId = 28,
                            ParentId = 25,
                            PermissionName = "DeleteCertificate",
                            PermissionTitle = "حذف مدرک"
                        },
                        new
                        {
                            PermissionId = 29,
                            ParentId = 25,
                            PermissionName = "DetailCertificate",
                            PermissionTitle = "جزئیات مدرک"
                        },
                        new
                        {
                            PermissionId = 30,
                            ParentId = 25,
                            PermissionName = "DeleteCertificateForever",
                            PermissionTitle = "حذف مطلق مدرک"
                        },
                        new
                        {
                            PermissionId = 31,
                            PermissionName = "ManageExperiences",
                            PermissionTitle = "مدیریت سابقه ها"
                        },
                        new
                        {
                            PermissionId = 32,
                            ParentId = 31,
                            PermissionName = "AddExperience",
                            PermissionTitle = "افزودن سابقه"
                        },
                        new
                        {
                            PermissionId = 33,
                            ParentId = 31,
                            PermissionName = "EditExperience",
                            PermissionTitle = "ویرایش سابقه"
                        },
                        new
                        {
                            PermissionId = 34,
                            ParentId = 31,
                            PermissionName = "DeleteExperience",
                            PermissionTitle = "حذف سابقه"
                        },
                        new
                        {
                            PermissionId = 35,
                            ParentId = 31,
                            PermissionName = "DetailExperience",
                            PermissionTitle = "جزئیات سابقه"
                        },
                        new
                        {
                            PermissionId = 36,
                            ParentId = 31,
                            PermissionName = "DeleteExperienceForever",
                            PermissionTitle = "حذف مطلق سابقه"
                        },
                        new
                        {
                            PermissionId = 37,
                            PermissionName = "ManageGyms",
                            PermissionTitle = "مدیریت باشگاه ها"
                        },
                        new
                        {
                            PermissionId = 38,
                            ParentId = 37,
                            PermissionName = "AddGym",
                            PermissionTitle = "افزودن باشگاه"
                        },
                        new
                        {
                            PermissionId = 39,
                            ParentId = 37,
                            PermissionName = "EditGym",
                            PermissionTitle = "ویرایش باشگاه"
                        },
                        new
                        {
                            PermissionId = 40,
                            ParentId = 37,
                            PermissionName = "DeleteGym",
                            PermissionTitle = "حذف باشگاه"
                        },
                        new
                        {
                            PermissionId = 41,
                            ParentId = 37,
                            PermissionName = "DeleteGymForever",
                            PermissionTitle = "حذف مطلق باشگاه"
                        },
                        new
                        {
                            PermissionId = 42,
                            ParentId = 37,
                            PermissionName = "GalleryGym",
                            PermissionTitle = "گالری باشگاه"
                        },
                        new
                        {
                            PermissionId = 43,
                            ParentId = 37,
                            PermissionName = "AddGalleryGym",
                            PermissionTitle = "افزودن گالری باشگاه"
                        },
                        new
                        {
                            PermissionId = 44,
                            ParentId = 37,
                            PermissionName = "DeleteGalleryGym",
                            PermissionTitle = "حذف گالری باشگاه"
                        },
                        new
                        {
                            PermissionId = 45,
                            PermissionName = "ManageSports",
                            PermissionTitle = "مدیریت رشته های ورزشی"
                        },
                        new
                        {
                            PermissionId = 46,
                            ParentId = 45,
                            PermissionName = "AddSport",
                            PermissionTitle = "افزودن رشته ورزشی"
                        },
                        new
                        {
                            PermissionId = 47,
                            ParentId = 45,
                            PermissionName = "EditSport",
                            PermissionTitle = "ویرایش رشته ورزشی"
                        },
                        new
                        {
                            PermissionId = 48,
                            ParentId = 45,
                            PermissionName = "DeleteSport",
                            PermissionTitle = "حذف رشته ورزشی"
                        },
                        new
                        {
                            PermissionId = 49,
                            ParentId = 45,
                            PermissionName = "DetailSport",
                            PermissionTitle = "جزئیات رشته ورزشی"
                        },
                        new
                        {
                            PermissionId = 50,
                            ParentId = 45,
                            PermissionName = "DeleteSportForever",
                            PermissionTitle = "حذف مطلق رشته ورزشی"
                        },
                        new
                        {
                            PermissionId = 51,
                            PermissionName = "ManageSportClasses",
                            PermissionTitle = "مدیریت کلاس های ورزشی"
                        },
                        new
                        {
                            PermissionId = 52,
                            ParentId = 51,
                            PermissionName = "AddSportClass",
                            PermissionTitle = "افزودن کلاس ورزشی"
                        },
                        new
                        {
                            PermissionId = 53,
                            ParentId = 51,
                            PermissionName = "EditSportClass",
                            PermissionTitle = "ویرایش کلاس ورزشی"
                        },
                        new
                        {
                            PermissionId = 54,
                            ParentId = 51,
                            PermissionName = "DeleteSportClass",
                            PermissionTitle = "حذف کلاس ورزشی"
                        },
                        new
                        {
                            PermissionId = 55,
                            ParentId = 51,
                            PermissionName = "DetailSportClass",
                            PermissionTitle = "جزئیات کلاس ورزشی"
                        },
                        new
                        {
                            PermissionId = 56,
                            ParentId = 51,
                            PermissionName = "DeleteSportClassForever",
                            PermissionTitle = "حذف مطلق کلاس ورزشی"
                        });
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("Situation")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("city")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("userRoles");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Gyms.GymGallery", b =>
                {
                    b.HasOne("Hexagon.Domain.Models.Gyms.Gym", "gym")
                        .WithMany("Gallery")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("gym");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Gyms.Sport", b =>
                {
                    b.HasOne("Hexagon.Domain.Models.Records.Certificate", "Certificate")
                        .WithMany("Sports")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Gyms.SportClass", b =>
                {
                    b.HasOne("Hexagon.Domain.Models.Gyms.Gym", "gym")
                        .WithMany("SportClasses")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hexagon.Domain.Models.Gyms.Sport", "sport")
                        .WithMany("Classes")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hexagon.Domain.Models.Users.Staff", "Trainer")
                        .WithMany("SportClasses")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");

                    b.Navigation("gym");

                    b.Navigation("sport");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Links.ClassUser", b =>
                {
                    b.HasOne("Hexagon.Domain.Models.Gyms.SportClass", "SportClass")
                        .WithMany("ClassUsers")
                        .HasForeignKey("SportClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hexagon.Domain.Models.Users.User", "user")
                        .WithMany("UserClasses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SportClass");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Links.GymStaff", b =>
                {
                    b.HasOne("Hexagon.Domain.Models.Gyms.Gym", "gym")
                        .WithMany("GymStaffs")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hexagon.Domain.Models.Users.Staff", "staff")
                        .WithMany("StaffGyms")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("gym");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Links.GymUser", b =>
                {
                    b.HasOne("Hexagon.Domain.Models.Gyms.Gym", "gym")
                        .WithMany("GymUsers")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hexagon.Domain.Models.Users.User", "user")
                        .WithMany("UserGyms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("gym");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Links.UserCertificates", b =>
                {
                    b.HasOne("Hexagon.Domain.Models.Records.Certificate", "certificate")
                        .WithMany("UserCertificates")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hexagon.Domain.Models.Users.Staff", "staff")
                        .WithMany("UserCertificates")
                        .HasForeignKey("StaffId");

                    b.HasOne("Hexagon.Domain.Models.Users.User", "user")
                        .WithMany("UserCertificates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("certificate");

                    b.Navigation("staff");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Records.Experience", b =>
                {
                    b.HasOne("Hexagon.Domain.Models.Records.Certificate", "certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId");

                    b.HasOne("Hexagon.Domain.Models.Users.User", "user")
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("certificate");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.Permission", b =>
                {
                    b.HasOne("Hexagon.Domain.Models.Users.Permission", "permission")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("permission");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.RolePermission", b =>
                {
                    b.HasOne("Hexagon.Domain.Models.Users.Permission", "permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hexagon.Domain.Models.Users.Role", "role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.Staff", b =>
                {
                    b.HasOne("Hexagon.Domain.Models.Users.User", "user")
                        .WithMany("staffes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.UserRole", b =>
                {
                    b.HasOne("Hexagon.Domain.Models.Users.Role", "role")
                        .WithMany("userRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hexagon.Domain.Models.Users.User", "user")
                        .WithMany("userRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Gyms.Gym", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("GymStaffs");

                    b.Navigation("GymUsers");

                    b.Navigation("SportClasses");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Gyms.Sport", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Gyms.SportClass", b =>
                {
                    b.Navigation("ClassUsers");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Records.Certificate", b =>
                {
                    b.Navigation("Sports");

                    b.Navigation("UserCertificates");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("userRoles");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.Staff", b =>
                {
                    b.Navigation("SportClasses");

                    b.Navigation("StaffGyms");

                    b.Navigation("UserCertificates");
                });

            modelBuilder.Entity("Hexagon.Domain.Models.Users.User", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("UserCertificates");

                    b.Navigation("UserClasses");

                    b.Navigation("UserGyms");

                    b.Navigation("staffes");

                    b.Navigation("userRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
