<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Convertors\" />
    <Folder Include="Extensions\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="kavenegar" Version="1.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hexagon.Infra.Data\Hexagon.Infra.Data.csproj" />
  </ItemGroup>

</Project>
