<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EasyCaching.Redis" Version="1.9.2" />
    <PackageReference Include="EasyCaching.Serialization.Json" Version="1.9.2" />
    <PackageReference Include="kavenegar" Version="1.2.4" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.0.0" />
    <PackageReference Include="Melipayamak.RestClient" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.3.0" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GreenHeart.Infra.Data\GreenHeart.Infra.Data.csproj" />
  </ItemGroup>

</Project>
