// <auto-generated />
using System;
using GreenHeart.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenHeart.Infra.Data.Migrations
{
    [DbContext(typeof(GreenHeartContext))]
    [Migration("20250711075914_adding_Essays_Permissions_Seed_Data")]
    partial class adding_Essays_Permissions_Seed_Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenHeart.Domain.Models.Banners.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Contact_Us.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LastModifiedBy");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Essays.Essay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EssayCagtegoryId")
                        .HasColumnType("int");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EssayCagtegoryId");

                    b.ToTable("Essays");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Essays.EssayCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EssayCategoryParentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EssayCategoryParentId");

                    b.ToTable("EssayCategories");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.ClassComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CommentStatus")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SportClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SportClassId");

                    b.ToTable("ClassComments");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.ClassCommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReactionType")
                        .HasColumnType("int");

                    b.Property<int>("SportClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SportClassId");

                    b.ToTable("ClassCommentReactions");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<int?>("Area")
                        .HasColumnType("int");

                    b.Property<string>("ConstantPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.HasKey("Id");

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.GymGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("GymGalleries");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificateId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.SportClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassStatus")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxSubscription")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<double>("SubscriptionFee")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("SportId");

                    b.HasIndex("TrainerId");

                    b.ToTable("SportClasses");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.KeyWords.KeyWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EssayId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("EssayId");

                    b.ToTable("KeyWords");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Links.ClassUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SportClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubscriptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportClassId");

                    b.HasIndex("UserId");

                    b.ToTable("ClassUsers");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Links.GymStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("StaffId");

                    b.ToTable("GymStaffs");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Links.GymUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("UserId");

                    b.ToTable("GymUsers");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Links.UserCertificates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfTake")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlaceOftake")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("StaffId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCertificates");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Links.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<int?>("CaderId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("CaderId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("userRoles");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Orders.ClassOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("OrderId");

                    b.ToTable("ClassOrders");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFainally")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Records.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Records.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CertificateId")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExImage")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("HowLong")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("RecordCategoryId");

                    b.HasIndex("StaffId");

                    b.HasIndex("UserId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Records.RecordCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("RecordCategories");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Tickets.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Tickets.TicketMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketMessages");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Users.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermissionId");

                    b.HasIndex("ParentId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            PermissionName = "ManageUsers",
                            PermissionTitle = "مدیریت کاربران"
                        },
                        new
                        {
                            PermissionId = 2,
                            ParentId = 1,
                            PermissionName = "AddUser",
                            PermissionTitle = "افزودن کاربر"
                        },
                        new
                        {
                            PermissionId = 3,
                            ParentId = 1,
                            PermissionName = "EditUser",
                            PermissionTitle = "ویرایش کاربر"
                        },
                        new
                        {
                            PermissionId = 4,
                            ParentId = 1,
                            PermissionName = "DeleteUser",
                            PermissionTitle = "حذف کاربر"
                        },
                        new
                        {
                            PermissionId = 5,
                            ParentId = 1,
                            PermissionName = "DetailUser",
                            PermissionTitle = "جزئیات کاربر"
                        },
                        new
                        {
                            PermissionId = 6,
                            ParentId = 1,
                            PermissionName = "DeleteUserForever",
                            PermissionTitle = "حذف مطلق کاربر"
                        },
                        new
                        {
                            PermissionId = 58,
                            ParentId = 1,
                            PermissionName = "ChangeUserPassword",
                            PermissionTitle = "تغییر رمز کاربر"
                        },
                        new
                        {
                            PermissionId = 7,
                            PermissionName = "ManageRoles",
                            PermissionTitle = "مدیریت نقش ها"
                        },
                        new
                        {
                            PermissionId = 8,
                            ParentId = 7,
                            PermissionName = "AddRole",
                            PermissionTitle = "افزودن نقش"
                        },
                        new
                        {
                            PermissionId = 9,
                            ParentId = 7,
                            PermissionName = "EditRole",
                            PermissionTitle = "ویرایش نقش"
                        },
                        new
                        {
                            PermissionId = 10,
                            ParentId = 7,
                            PermissionName = "DeleteRole",
                            PermissionTitle = "حذف نقش"
                        },
                        new
                        {
                            PermissionId = 11,
                            ParentId = 7,
                            PermissionName = "DetailRole",
                            PermissionTitle = "جزئیات نقش"
                        },
                        new
                        {
                            PermissionId = 12,
                            ParentId = 7,
                            PermissionName = "DeleteRoleForever",
                            PermissionTitle = "حذف مطلق نقش"
                        },
                        new
                        {
                            PermissionId = 13,
                            PermissionName = "ManageTrainers",
                            PermissionTitle = "مدیریت مربی ها"
                        },
                        new
                        {
                            PermissionId = 14,
                            ParentId = 13,
                            PermissionName = "AddTrainer",
                            PermissionTitle = "افزودن مربی"
                        },
                        new
                        {
                            PermissionId = 15,
                            ParentId = 13,
                            PermissionName = "EditTrainer",
                            PermissionTitle = "ویرایش مربی"
                        },
                        new
                        {
                            PermissionId = 16,
                            ParentId = 13,
                            PermissionName = "DeleteTrainer",
                            PermissionTitle = "حذف مربی"
                        },
                        new
                        {
                            PermissionId = 17,
                            ParentId = 13,
                            PermissionName = "DetailTrainer",
                            PermissionTitle = "جزئیات مربی"
                        },
                        new
                        {
                            PermissionId = 18,
                            ParentId = 13,
                            PermissionName = "DeleteTrainerForever",
                            PermissionTitle = "حذف مطلق مربی"
                        },
                        new
                        {
                            PermissionId = 19,
                            PermissionName = "ManageCaders",
                            PermissionTitle = "مدیریت کادرها"
                        },
                        new
                        {
                            PermissionId = 20,
                            ParentId = 19,
                            PermissionName = "AddCader",
                            PermissionTitle = "افزودن کادر"
                        },
                        new
                        {
                            PermissionId = 21,
                            ParentId = 19,
                            PermissionName = "EditCader",
                            PermissionTitle = "ویرایش کادر"
                        },
                        new
                        {
                            PermissionId = 22,
                            ParentId = 19,
                            PermissionName = "DeleteCader",
                            PermissionTitle = "حذف کادر"
                        },
                        new
                        {
                            PermissionId = 23,
                            ParentId = 19,
                            PermissionName = "DetailCader",
                            PermissionTitle = "جزئیات کادر"
                        },
                        new
                        {
                            PermissionId = 24,
                            ParentId = 19,
                            PermissionName = "DeleteCaderForever",
                            PermissionTitle = "حذف مطلق کادر"
                        },
                        new
                        {
                            PermissionId = 25,
                            PermissionName = "ManageCertificates",
                            PermissionTitle = "مدیریت مدرک ها"
                        },
                        new
                        {
                            PermissionId = 26,
                            ParentId = 25,
                            PermissionName = "AddCertificate",
                            PermissionTitle = "افزودن مدرک"
                        },
                        new
                        {
                            PermissionId = 27,
                            ParentId = 25,
                            PermissionName = "EditCertificate",
                            PermissionTitle = "ویرایش مدرک"
                        },
                        new
                        {
                            PermissionId = 28,
                            ParentId = 25,
                            PermissionName = "DeleteCertificate",
                            PermissionTitle = "حذف مدرک"
                        },
                        new
                        {
                            PermissionId = 29,
                            ParentId = 25,
                            PermissionName = "DetailCertificate",
                            PermissionTitle = "جزئیات مدرک"
                        },
                        new
                        {
                            PermissionId = 30,
                            ParentId = 25,
                            PermissionName = "DeleteCertificateForever",
                            PermissionTitle = "حذف مطلق مدرک"
                        },
                        new
                        {
                            PermissionId = 31,
                            PermissionName = "ManageExperiences",
                            PermissionTitle = "مدیریت سابقه ها"
                        },
                        new
                        {
                            PermissionId = 32,
                            ParentId = 31,
                            PermissionName = "AddExperience",
                            PermissionTitle = "افزودن سابقه"
                        },
                        new
                        {
                            PermissionId = 33,
                            ParentId = 31,
                            PermissionName = "EditExperience",
                            PermissionTitle = "ویرایش سابقه"
                        },
                        new
                        {
                            PermissionId = 34,
                            ParentId = 31,
                            PermissionName = "DeleteExperience",
                            PermissionTitle = "حذف سابقه"
                        },
                        new
                        {
                            PermissionId = 35,
                            ParentId = 31,
                            PermissionName = "DetailExperience",
                            PermissionTitle = "جزئیات سابقه"
                        },
                        new
                        {
                            PermissionId = 36,
                            ParentId = 31,
                            PermissionName = "DeleteExperienceForever",
                            PermissionTitle = "حذف مطلق سابقه"
                        },
                        new
                        {
                            PermissionId = 92,
                            PermissionName = "ManageRecordCategories",
                            PermissionTitle = "مدیریت مجموعه های سوابق"
                        },
                        new
                        {
                            PermissionId = 93,
                            ParentId = 92,
                            PermissionName = "AddRecordCategory",
                            PermissionTitle = "افزودن مجموعه سوابق"
                        },
                        new
                        {
                            PermissionId = 94,
                            ParentId = 92,
                            PermissionName = "EditRecordCategory",
                            PermissionTitle = "ویرایش مجموعه سوابق"
                        },
                        new
                        {
                            PermissionId = 95,
                            ParentId = 92,
                            PermissionName = "DeleteRecordCategory",
                            PermissionTitle = "حذف مجموعه سوابق"
                        },
                        new
                        {
                            PermissionId = 96,
                            ParentId = 92,
                            PermissionName = "DetailRecordCategory",
                            PermissionTitle = "جزئیات مجموعه سوابق"
                        },
                        new
                        {
                            PermissionId = 97,
                            ParentId = 92,
                            PermissionName = "DeleteRecordCategoryForever",
                            PermissionTitle = "حذف مطلق مجموعه سوابق"
                        },
                        new
                        {
                            PermissionId = 37,
                            PermissionName = "ManageGyms",
                            PermissionTitle = "مدیریت باشگاه ها"
                        },
                        new
                        {
                            PermissionId = 38,
                            ParentId = 37,
                            PermissionName = "AddGym",
                            PermissionTitle = "افزودن باشگاه"
                        },
                        new
                        {
                            PermissionId = 39,
                            ParentId = 37,
                            PermissionName = "EditGym",
                            PermissionTitle = "ویرایش باشگاه"
                        },
                        new
                        {
                            PermissionId = 40,
                            ParentId = 37,
                            PermissionName = "DeleteGym",
                            PermissionTitle = "حذف باشگاه"
                        },
                        new
                        {
                            PermissionId = 57,
                            ParentId = 37,
                            PermissionName = "DetailGym",
                            PermissionTitle = "جزئیات باشگاه"
                        },
                        new
                        {
                            PermissionId = 41,
                            ParentId = 37,
                            PermissionName = "DeleteGymForever",
                            PermissionTitle = "حذف مطلق باشگاه"
                        },
                        new
                        {
                            PermissionId = 42,
                            ParentId = 37,
                            PermissionName = "GalleryGym",
                            PermissionTitle = "گالری باشگاه"
                        },
                        new
                        {
                            PermissionId = 43,
                            ParentId = 37,
                            PermissionName = "AddGalleryGym",
                            PermissionTitle = "افزودن گالری باشگاه"
                        },
                        new
                        {
                            PermissionId = 44,
                            ParentId = 37,
                            PermissionName = "DeleteGalleryGym",
                            PermissionTitle = "حذف گالری باشگاه"
                        },
                        new
                        {
                            PermissionId = 45,
                            PermissionName = "ManageSports",
                            PermissionTitle = "مدیریت رشته های ورزشی"
                        },
                        new
                        {
                            PermissionId = 46,
                            ParentId = 45,
                            PermissionName = "AddSport",
                            PermissionTitle = "افزودن رشته ورزشی"
                        },
                        new
                        {
                            PermissionId = 47,
                            ParentId = 45,
                            PermissionName = "EditSport",
                            PermissionTitle = "ویرایش رشته ورزشی"
                        },
                        new
                        {
                            PermissionId = 48,
                            ParentId = 45,
                            PermissionName = "DeleteSport",
                            PermissionTitle = "حذف رشته ورزشی"
                        },
                        new
                        {
                            PermissionId = 49,
                            ParentId = 45,
                            PermissionName = "DetailSport",
                            PermissionTitle = "جزئیات رشته ورزشی"
                        },
                        new
                        {
                            PermissionId = 50,
                            ParentId = 45,
                            PermissionName = "DeleteSportForever",
                            PermissionTitle = "حذف مطلق رشته ورزشی"
                        },
                        new
                        {
                            PermissionId = 51,
                            PermissionName = "ManageSportClasses",
                            PermissionTitle = "مدیریت کلاس های ورزشی"
                        },
                        new
                        {
                            PermissionId = 52,
                            ParentId = 51,
                            PermissionName = "AddSportClass",
                            PermissionTitle = "افزودن کلاس ورزشی"
                        },
                        new
                        {
                            PermissionId = 53,
                            ParentId = 51,
                            PermissionName = "EditSportClass",
                            PermissionTitle = "ویرایش کلاس ورزشی"
                        },
                        new
                        {
                            PermissionId = 54,
                            ParentId = 51,
                            PermissionName = "DeleteSportClass",
                            PermissionTitle = "حذف کلاس ورزشی"
                        },
                        new
                        {
                            PermissionId = 55,
                            ParentId = 51,
                            PermissionName = "DetailSportClass",
                            PermissionTitle = "جزئیات کلاس ورزشی"
                        },
                        new
                        {
                            PermissionId = 56,
                            ParentId = 51,
                            PermissionName = "DeleteSportClassForever",
                            PermissionTitle = "حذف مطلق کلاس ورزشی"
                        },
                        new
                        {
                            PermissionId = 86,
                            PermissionName = "ManageClassComments",
                            PermissionTitle = "مدیریت نظرات کلاس ها"
                        },
                        new
                        {
                            PermissionId = 87,
                            ParentId = 86,
                            PermissionName = "GetComments",
                            PermissionTitle = "مشاهده نظر"
                        },
                        new
                        {
                            PermissionId = 88,
                            ParentId = 86,
                            PermissionName = "ChangeCommentStatus",
                            PermissionTitle = "تغییر وضعیت نظر"
                        },
                        new
                        {
                            PermissionId = 89,
                            ParentId = 86,
                            PermissionName = "DeleteComment",
                            PermissionTitle = "حذف نظر"
                        },
                        new
                        {
                            PermissionId = 90,
                            ParentId = 86,
                            PermissionName = "DetailComment",
                            PermissionTitle = "جزئیات نظر"
                        },
                        new
                        {
                            PermissionId = 91,
                            ParentId = 86,
                            PermissionName = "DeleteCommentForever",
                            PermissionTitle = "حذف مطلق نظر"
                        },
                        new
                        {
                            PermissionId = 59,
                            PermissionName = "ManageBanners",
                            PermissionTitle = "مدیریت بنرها"
                        },
                        new
                        {
                            PermissionId = 60,
                            ParentId = 59,
                            PermissionName = "AddBanner",
                            PermissionTitle = "افزودن بنر"
                        },
                        new
                        {
                            PermissionId = 61,
                            ParentId = 59,
                            PermissionName = "DeleteBanner",
                            PermissionTitle = "افزودن بنر"
                        },
                        new
                        {
                            PermissionId = 62,
                            PermissionName = "ManageContactUses",
                            PermissionTitle = "مدیریت ارتباط با ما"
                        },
                        new
                        {
                            PermissionId = 63,
                            ParentId = 62,
                            PermissionName = "AnswerContactUs",
                            PermissionTitle = "ویرایش ارتباط با ما"
                        },
                        new
                        {
                            PermissionId = 64,
                            ParentId = 62,
                            PermissionName = "DeleteContactUs",
                            PermissionTitle = "حذف ارتباط با ما"
                        },
                        new
                        {
                            PermissionId = 65,
                            ParentId = 62,
                            PermissionName = "DetailContactUs",
                            PermissionTitle = "جزئیات ارتباط با ما"
                        },
                        new
                        {
                            PermissionId = 66,
                            ParentId = 62,
                            PermissionName = "DeleteContactUsForever",
                            PermissionTitle = "حذف مطلق ارتباط با ما"
                        },
                        new
                        {
                            PermissionId = 67,
                            PermissionName = "ManageKeyWords",
                            PermissionTitle = "مدیریت کلمات کلیدی"
                        },
                        new
                        {
                            PermissionId = 68,
                            ParentId = 67,
                            PermissionName = "AddKeyWord",
                            PermissionTitle = "افزودن کلمه کلیدی"
                        },
                        new
                        {
                            PermissionId = 69,
                            ParentId = 67,
                            PermissionName = "EditKeyWord",
                            PermissionTitle = "ویرایش کلمه کلیدی"
                        },
                        new
                        {
                            PermissionId = 70,
                            ParentId = 67,
                            PermissionName = "DeleteKeyWord",
                            PermissionTitle = "حذف کلمه کلیدی"
                        },
                        new
                        {
                            PermissionId = 71,
                            ParentId = 67,
                            PermissionName = "DetailKeyWord",
                            PermissionTitle = "جزئیات کلمه کلیدی"
                        },
                        new
                        {
                            PermissionId = 72,
                            ParentId = 67,
                            PermissionName = "DeleteKeyWordForever",
                            PermissionTitle = "حذف مطلق کلمه کلیدی"
                        },
                        new
                        {
                            PermissionId = 73,
                            PermissionName = "ManageTickets",
                            PermissionTitle = "مدیریت تیکت ها"
                        },
                        new
                        {
                            PermissionId = 74,
                            ParentId = 73,
                            PermissionName = "AnswerTicket",
                            PermissionTitle = "پاسخ تیکت"
                        },
                        new
                        {
                            PermissionId = 75,
                            ParentId = 73,
                            PermissionName = "ChangeTicketStatus",
                            PermissionTitle = "تغییر وضعیت تیکت"
                        },
                        new
                        {
                            PermissionId = 76,
                            ParentId = 73,
                            PermissionName = "DeleteTicket",
                            PermissionTitle = "حذف تیکت"
                        },
                        new
                        {
                            PermissionId = 77,
                            ParentId = 73,
                            PermissionName = "DetailTicket",
                            PermissionTitle = "جزئیات تیکت"
                        },
                        new
                        {
                            PermissionId = 78,
                            ParentId = 73,
                            PermissionName = "DeleteTicketForever",
                            PermissionTitle = "حذف مطلق تیکت"
                        },
                        new
                        {
                            PermissionId = 79,
                            ParentId = 73,
                            PermissionName = "DeleteTicketMessage",
                            PermissionTitle = "حذف پیام تیکت"
                        },
                        new
                        {
                            PermissionId = 80,
                            ParentId = 73,
                            PermissionName = "DeleteTicketMessageForever",
                            PermissionTitle = "حذف مطلق پیام تیکت"
                        },
                        new
                        {
                            PermissionId = 81,
                            PermissionName = "ManageWallets",
                            PermissionTitle = "مدیریت کیف پول ها"
                        },
                        new
                        {
                            PermissionId = 82,
                            ParentId = 81,
                            PermissionName = "ChargeUserWallet",
                            PermissionTitle = "شارژ کیف پول کاربر"
                        },
                        new
                        {
                            PermissionId = 83,
                            ParentId = 81,
                            PermissionName = "DetailWallet",
                            PermissionTitle = "جزئیات کیف پول"
                        },
                        new
                        {
                            PermissionId = 84,
                            PermissionName = "ManageOrders",
                            PermissionTitle = "مدیریت فاکتور ها"
                        },
                        new
                        {
                            PermissionId = 85,
                            ParentId = 84,
                            PermissionName = "DetailOrder",
                            PermissionTitle = "جزئیات فاکتور"
                        },
                        new
                        {
                            PermissionId = 98,
                            PermissionName = "ManageEssayCategories",
                            PermissionTitle = "مدیریت گروه های مقالات"
                        },
                        new
                        {
                            PermissionId = 99,
                            ParentId = 98,
                            PermissionName = "AddEssayCategory",
                            PermissionTitle = "افزودن گروه مقاله"
                        },
                        new
                        {
                            PermissionId = 100,
                            ParentId = 98,
                            PermissionName = "EditEssayCategory",
                            PermissionTitle = "ویرایش گروه مقاله"
                        },
                        new
                        {
                            PermissionId = 101,
                            ParentId = 98,
                            PermissionName = "DeleteEssayCategory",
                            PermissionTitle = "حذف گروه مقاله"
                        },
                        new
                        {
                            PermissionId = 102,
                            ParentId = 98,
                            PermissionName = "DetailEssayCategory",
                            PermissionTitle = "جزئیات گروه مقاله"
                        },
                        new
                        {
                            PermissionId = 103,
                            ParentId = 98,
                            PermissionName = "DeleteEssayCategoryForever",
                            PermissionTitle = "حذف مطلق گروه مقاله"
                        },
                        new
                        {
                            PermissionId = 104,
                            PermissionName = "ManageEssays",
                            PermissionTitle = "مدیریت مقالات"
                        },
                        new
                        {
                            PermissionId = 105,
                            ParentId = 104,
                            PermissionName = "AddEssay",
                            PermissionTitle = "افزودن مقاله"
                        },
                        new
                        {
                            PermissionId = 106,
                            ParentId = 104,
                            PermissionName = "EditEssay",
                            PermissionTitle = "ویرایش مقاله"
                        },
                        new
                        {
                            PermissionId = 107,
                            ParentId = 104,
                            PermissionName = "DeleteEssay",
                            PermissionTitle = "حذف مقاله"
                        },
                        new
                        {
                            PermissionId = 108,
                            ParentId = 104,
                            PermissionName = "DetailEssay",
                            PermissionTitle = "جزئیات مقاله"
                        },
                        new
                        {
                            PermissionId = 109,
                            ParentId = 104,
                            PermissionName = "DeleteEssayForever",
                            PermissionTitle = "حذف مطلق مقاله"
                        });
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Users.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Users.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("Situation")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("city")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Wallets.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Authority")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Case")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPayed")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("RefId")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Contact_Us.ContactUs", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Users.User", "AnsweredUser")
                        .WithMany("AnswersContactUs")
                        .HasForeignKey("LastModifiedBy");

                    b.Navigation("AnsweredUser");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Essays.Essay", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Essays.EssayCategory", "essayCategory")
                        .WithMany("Essays")
                        .HasForeignKey("EssayCagtegoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("essayCategory");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Essays.EssayCategory", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Essays.EssayCategory", "CategoryParent")
                        .WithMany("CategoryChilds")
                        .HasForeignKey("EssayCategoryParentId");

                    b.Navigation("CategoryParent");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.ClassComment", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Users.User", "User")
                        .WithMany("ClassComments")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("GreenHeart.Domain.Models.Gyms.SportClass", "sportClass")
                        .WithMany("ClassComments")
                        .HasForeignKey("SportClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("sportClass");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.ClassCommentReaction", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Gyms.ClassComment", "Comment")
                        .WithMany("CommentReactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenHeart.Domain.Models.Users.User", "User")
                        .WithMany("ClassCommentReactions")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("GreenHeart.Domain.Models.Gyms.SportClass", "SportClass")
                        .WithMany("ClassCommentReactions")
                        .HasForeignKey("SportClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("SportClass");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.GymGallery", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Gyms.Gym", "gym")
                        .WithMany("Gallery")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("gym");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.Sport", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Records.Certificate", "Certificate")
                        .WithMany("Sports")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.SportClass", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Gyms.Gym", "gym")
                        .WithMany("SportClasses")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenHeart.Domain.Models.Gyms.Sport", "sport")
                        .WithMany("Classes")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenHeart.Domain.Models.Users.Staff", "Trainer")
                        .WithMany("SportClasses")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");

                    b.Navigation("gym");

                    b.Navigation("sport");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.KeyWords.KeyWord", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Gyms.SportClass", "sportClass")
                        .WithMany("KeyWords")
                        .HasForeignKey("ClassId");

                    b.HasOne("GreenHeart.Domain.Models.Essays.Essay", "Essay")
                        .WithMany("keyWords")
                        .HasForeignKey("EssayId");

                    b.Navigation("Essay");

                    b.Navigation("sportClass");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Links.ClassUser", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Gyms.SportClass", "SportClass")
                        .WithMany("ClassUsers")
                        .HasForeignKey("SportClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenHeart.Domain.Models.Users.User", "user")
                        .WithMany("UserClasses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SportClass");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Links.GymStaff", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Gyms.Gym", "gym")
                        .WithMany("GymStaffs")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenHeart.Domain.Models.Users.Staff", "staff")
                        .WithMany("StaffGyms")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("gym");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Links.GymUser", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Gyms.Gym", "gym")
                        .WithMany("GymUsers")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenHeart.Domain.Models.Users.User", "user")
                        .WithMany("UserGyms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("gym");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Links.UserCertificates", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Records.Certificate", "certificate")
                        .WithMany("UserCertificates")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenHeart.Domain.Models.Users.Staff", "staff")
                        .WithMany("UserCertificates")
                        .HasForeignKey("StaffId");

                    b.HasOne("GreenHeart.Domain.Models.Users.User", "user")
                        .WithMany("UserCertificates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("certificate");

                    b.Navigation("staff");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Links.UserRole", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Users.Staff", "Cader")
                        .WithMany("userRoles")
                        .HasForeignKey("CaderId");

                    b.HasOne("GreenHeart.Domain.Models.Users.Role", "role")
                        .WithMany("userRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenHeart.Domain.Models.Users.User", "user")
                        .WithMany("userRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cader");

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Orders.ClassOrder", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Gyms.SportClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenHeart.Domain.Models.Orders.Order", "order")
                        .WithMany("ClassesOrder")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("order");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Orders.Order", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Users.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("CreatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Records.Experience", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Records.Certificate", "certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId");

                    b.HasOne("GreenHeart.Domain.Models.Records.RecordCategory", "recordCategory")
                        .WithMany("Experiences")
                        .HasForeignKey("RecordCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenHeart.Domain.Models.Users.Staff", "staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenHeart.Domain.Models.Users.User", "user")
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("certificate");

                    b.Navigation("recordCategory");

                    b.Navigation("staff");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Records.RecordCategory", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Users.Staff", "Trainer")
                        .WithMany("RecordCategories")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Tickets.Ticket", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Users.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("CreatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Tickets.TicketMessage", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Users.User", "Sender")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("GreenHeart.Domain.Models.Tickets.Ticket", "Ticket")
                        .WithMany("TicketMessages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Users.Permission", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Users.Permission", "permission")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("permission");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Users.RolePermission", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Users.Permission", "permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenHeart.Domain.Models.Users.Role", "role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Users.Staff", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Users.User", "user")
                        .WithMany("staffes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Wallets.Wallet", b =>
                {
                    b.HasOne("GreenHeart.Domain.Models.Orders.Order", "Order")
                        .WithMany("Wallets")
                        .HasForeignKey("OrderId");

                    b.HasOne("GreenHeart.Domain.Models.Users.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Essays.Essay", b =>
                {
                    b.Navigation("keyWords");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Essays.EssayCategory", b =>
                {
                    b.Navigation("CategoryChilds");

                    b.Navigation("Essays");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.ClassComment", b =>
                {
                    b.Navigation("CommentReactions");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.Gym", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("GymStaffs");

                    b.Navigation("GymUsers");

                    b.Navigation("SportClasses");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.Sport", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Gyms.SportClass", b =>
                {
                    b.Navigation("ClassCommentReactions");

                    b.Navigation("ClassComments");

                    b.Navigation("ClassUsers");

                    b.Navigation("KeyWords");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Orders.Order", b =>
                {
                    b.Navigation("ClassesOrder");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Records.Certificate", b =>
                {
                    b.Navigation("Sports");

                    b.Navigation("UserCertificates");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Records.RecordCategory", b =>
                {
                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Tickets.Ticket", b =>
                {
                    b.Navigation("TicketMessages");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Users.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Users.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("userRoles");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Users.Staff", b =>
                {
                    b.Navigation("RecordCategories");

                    b.Navigation("SportClasses");

                    b.Navigation("StaffGyms");

                    b.Navigation("UserCertificates");

                    b.Navigation("userRoles");
                });

            modelBuilder.Entity("GreenHeart.Domain.Models.Users.User", b =>
                {
                    b.Navigation("AnswersContactUs");

                    b.Navigation("ClassCommentReactions");

                    b.Navigation("ClassComments");

                    b.Navigation("Experiences");

                    b.Navigation("Orders");

                    b.Navigation("Tickets");

                    b.Navigation("UserCertificates");

                    b.Navigation("UserClasses");

                    b.Navigation("UserGyms");

                    b.Navigation("Wallets");

                    b.Navigation("staffes");

                    b.Navigation("userRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
